# NumPy Data Explorer

**Project - 1**

This project demonstrates fundamental NumPy operations including array creation, indexing, slicing, mathematical operations, reshaping, broadcasting, and performance comparison with Python lists.


## 1. Importing NumPy


In [2]:
import numpy as np

## 2. Array Creation


In [3]:
# 1D array
arr1 = np.array([10, 20, 30, 40, 50])

# 2D array
arr2 = np.arange(1, 13).reshape(3, 4)

arr1, arr2


(array([10, 20, 30, 40, 50]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

## 3. Indexing and Slicing

In [4]:
# Indexing
arr1[2]


np.int64(30)

In [5]:
# Slicing
arr1[1:4]


array([20, 30, 40])

In [6]:
# Column slicing from 2D array
arr2[:, 1]


array([ 2,  6, 10])

## 4. Mathematical Operations

In [7]:
arr1 + 5



array([15, 25, 35, 45, 55])

In [8]:
arr1 * 2


array([ 20,  40,  60,  80, 100])

In [9]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

## 5. Axis-wise Operations

In [10]:
# Column-wise sum
arr2.sum(axis=0)


array([15, 18, 21, 24])

In [11]:
# Row-wise sum
arr2.sum(axis=1)


array([10, 26, 42])

## 6. Statistical Operations

In [12]:
np.mean(arr1)


np.float64(30.0)

In [13]:
np.median(arr1)


np.float64(30.0)

In [14]:
np.std(arr1)


np.float64(14.142135623730951)

## 7. Reshaping and Broadcasting

In [15]:
reshaped_arr = arr1.reshape(5, 1)
reshaped_arr


array([[10],
       [20],
       [30],
       [40],
       [50]])

In [16]:
broadcasted_arr = arr2 + np.array([1, 2, 3, 4])
broadcasted_arr


array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

## 8. Saving and Loading NumPy Arrays

In [17]:
np.save("data/saved_array.npy", arr1)


In [18]:
loaded_array = np.load("data/saved_array.npy")
loaded_array


array([10, 20, 30, 40, 50])

## 9. Performance Comparison: NumPy vs Python Lists

In [19]:
import time

# Python list
py_list = list(range(1000000))

start = time.time()
py_list = [x * 2 for x in py_list]
python_time = time.time() - start

# NumPy array
np_array = np.arange(1000000)

start = time.time()
np_array = np_array * 2
numpy_time = time.time() - start

python_time, numpy_time


(0.22270560264587402, 0.012969732284545898)